config/routes.rb
Test1::Application.routes.draw do

	
 
 match '/users/:user_id/courses/update_courses' => 'courses#update_courses'
 
  resources :users do
    resources :courses
  end
  
  
  
	get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"
	
  resources :sessions
  
  root :to => "sessions#new"

end

app/models/course.rb
require 'url_validator'

class Course < ActiveRecord::Base
  
  belongs_to :user
  attr_accessible :name, :weblink, :html_source, :updated
  
  validates :name, :presence => true
  validates :weblink, :presence => true, :url => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :pass
  
  validates :name, :presence => true, :uniqueness => true, :length => {:minimum => 5}
  validates :pass, :presence => true, :length => {:minimum => 6}
    
  has_many :courses, :dependent => :destroy
  
  def self.authenticate(name, pass)
    user = find_by_name(name)
    if user && user.pass == pass
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	helper_method :current_user

	private

	def current_user
		begin
			@current_user ||= User.find(session[:user_id]) if session[:user_id]
		rescue ActiveRecord::RecordNotFound
			return false
		end	
	end
	
end

app/controllers/courses_controller.rb
require 'open-uri'

class CoursesController < ApplicationController
#  def create
#    @user = User.find(params[:user_id])
#    @course = @user.courses.create(params[:course])
#    weblink = @course.weblink
#    begin
#      html = open(weblink) {|f| f.read}
#    rescue Errno::ENOENT
#      logger.info "Malformed or unavailable URL"
#    end
#    @course.update_attributes({:html_source => html, :updated => false})
#    redirect_to user_path(@user)
#  end
  
  def create
    @user = User.find(params[:user_id])
    @course = @user.courses.build(params[:course])
    @course.updated = false
    weblink = @course.weblink
    begin
      html = open(weblink) {|f| f.read}
    rescue Errno::ENOENT
      logger.info "Malformed or unavailable URL"
    end
    
    respond_to do |format|

      if @course.save
        format.html {redirect_to user_path(@user), :notice => 'Course was successfully added.'}
      else
        format.html {render :action => '../users/show'}
        format.json {render :json => @course.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  
  
  def destroy
    @user = User.find(params[:user_id])
    @course = @user.courses.find(params[:id])
    @course.destroy
    redirect_to user_path(@user)
  end
  
  def update_courses
    @user = User.find(params[:user_id])
    @user.courses.each do |c| 
    weblink = c.weblink
      html = open(weblink) {|f| f.read}
      if html != c.html_source
        c.update_attributes({:html_source => html, :updated => true})
      else
        c.update_attributes({:updated => false})
      end
   end
      redirect_to user_path(@user)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
  user = User.authenticate(params[:name], params[:pass])
  if user
    session[:user_id] = user.id
    redirect_to user, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to :root }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  def update_courses_link_path(user_id)
    s = '/users/' + user_id.to_s + '/courses/update_courses'
    return s
  end
end

app/helpers/home_helper.rb
module HomeHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_course.html.erb
<p>


		<tr>
			<td>
					<%= link_to course.name, course.weblink %>
			</td>			
			<td>
					<% if course.updated %>
						No new updates!
					<% else %>
						Course Website has changed!
					<% end %>
			</td>
			<td>
					<%= link_to 'Delete', [course.user, course],
										:confirm => 'Are you sure you want to delete this course?',
										:method => :delete	 %>
			</td>	
</p>

app/views/courses/_form.html.erb
<%= form_for([@user, @user.courses.build]) do |f| %>
  <% if @course.respond_to?(:errors) && @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :weblink %><br />
		Example: "http://www.example.com"<br />
		<%= f.text_field :weblink %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>
<%= render 'form' %>

<%= link_to 'Back to Course Listing', user_path(@user) %>

app/views/home/index.html.erb
<h1><div align="center">Let's test this!</div></h1>
<%= link_to "User List", users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Course WebCheck</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user  %>
    <p style="border-bottom-style:dashed;border-width:1px;">
	    Logged in as <%= current_user.name %>.
	    <%= link_to "Log out", log_out_path %>
	    || <%= link_to "Delete Account", current_user,
			:confirm => 'Are you sure you want to delete your account?',
			:method => :delete %>
    </p>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :login, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pass %><br />
    <%= f.text_field :pass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h2>Courses</h2>

<% if !@user.courses.empty? %>
	<%= link_to 'Check all courses for updates', update_courses_link_path(@user.id) %>
	<% if @user.courses.first.name!='' %>
		<table> 
		<tr>
			<td>
				Course Title
			</td>
			<td>
				Updated Since last check?
			</td>
			<td>
				Delete Course From Listing
			</td>
		</tr>
		<%= render @user.courses %>
		</tr>
		</table>
	<% end %>
<% else %>
	No Courses Added! To Add a course, enter its information below.
<% end %>
<h2>Add a new course:</h2>
<%= render 'courses/form' %>


<%= link_to 'View/Change Password', edit_user_path(@user) %> 